version: "3.9"

services:

  service_a:
    build: ./service_a
    container_name: service_a
    ports:
      - "5001:5001"

  service_b:
    build: ./service_b
    container_name: service_b
    ports:
      - "7000:7000"
    depends_on:
      - service_a
