version: "3.8"

services:

  users_service:
    build: ./users_service
    container_name: d5-users
    ports:
      - "5003:5003"

  orders_service:
    build: ./orders_service
    container_name: d5-orders
    ports:
      - "5002:5002"

  gateway:
    build: ./gateway
    container_name: d5-gateway
    ports:
      - "5004:5004" 
    depends_on:
      - users_service
      - orders_service
